package pme123.geak4s.services

import scala.concurrent.Future
import scala.scalajs.concurrent.JSExecutionContext.Implicits.queue
import scala.scalajs.js
import org.scalajs.dom

/** Generates the Berechnungstool 260 XLSX from a serialized [[pme123.geak4s.domain.GeakProject]].
 *
 *  Dummy implementation: returns a small placeholder blob so the UI flow
 *  (download trigger, file naming) can be exercised without a backend.
 *  The real implementation will use ExcelJS on `Berechnungstool_260.xlsx`
 *  shipped under `public/templates/`, preserving its formulas and Excel Tables.
 */
object BerechnungstoolExportService:

  private val XlsxMimeType =
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"

  def generate(projectJson: String): Future[dom.Blob] =
    dom.console.log(
      s"[BerechnungstoolExportService] dummy generate (${projectJson.length} chars input)"
    )
    val placeholder =
      s"""DUMMY XLSX placeholder generated by BerechnungstoolExportService.
         |
         |This is not a real Excel file yet — the ExcelJS wiring is the next step.
         |
         |Project JSON (truncated):
         |${projectJson.take(500)}
         |""".stripMargin
    val blob = new dom.Blob(
      js.Array(placeholder),
      dom.BlobPropertyBag(XlsxMimeType)
    )
    Future.successful(blob)
end BerechnungstoolExportService
