package pme123.geak4s.services

import scala.concurrent.Future
import scala.scalajs.concurrent.JSExecutionContext.Implicits.queue
import scala.scalajs.js
import org.scalajs.dom

/** Generates the GEAK Excel export from a serialized [[pme123.geak4s.domain.GeakProject]].
 *
 *  Dummy implementation: returns a small placeholder blob so the UI flow
 *  (download trigger, file naming) can be exercised without a backend.
 *  The real implementation will use ExcelJS on the `GEAK-EXCEL-template.xlsx`
 *  shipped under `public/templates/`.
 */
object ExcelExportService:

  private val XlsMimeType = "application/vnd.ms-excel"

  def generate(projectJson: String): Future[dom.Blob] =
    dom.console.log(
      s"[ExcelExportService] dummy generate (${projectJson.length} chars input)"
    )
    val placeholder =
      s"""DUMMY XLS placeholder generated by ExcelExportService.
         |
         |This is not a real Excel file yet — the ExcelJS wiring is the next step.
         |
         |Project JSON (truncated):
         |${projectJson.take(500)}
         |""".stripMargin
    val blob = new dom.Blob(
      js.Array(placeholder),
      dom.BlobPropertyBag(XlsMimeType)
    )
    Future.successful(blob)
end ExcelExportService
