package pme123.geak4s.services

import scala.concurrent.Future
import scala.scalajs.concurrent.JSExecutionContext.Implicits.queue
import scala.scalajs.js
import org.scalajs.dom
import pme123.geak4s.domain.project.WordFormData

/** Generates the Begehungsprotokoll DOCX from a [[WordFormData]] form on the client.
 *
 *  Dummy implementation: returns a small placeholder blob so the UI flow
 *  (download trigger, file naming) can be exercised without a backend.
 *  The real implementation will use docxtemplater + pizzip on a `.docx` template
 *  shipped under `public/templates/`.
 */
object WordExportService:

  private val DocxMimeType =
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document"

  def generate(formData: WordFormData): Future[dom.Blob] =
    dom.console.log(
      s"[WordExportService] dummy generate (projektnummer=${formData.projektnummer})"
    )
    val placeholder =
      s"""DUMMY DOCX placeholder generated by WordExportService.
         |
         |This is not a real Word document yet — the docxtemplater wiring is the next step.
         |
         |Form data:
         |${formData.toString}
         |""".stripMargin
    val blob = new dom.Blob(
      js.Array(placeholder),
      dom.BlobPropertyBag(DocxMimeType)
    )
    Future.successful(blob)
end WordExportService
